spring:
  application:
    name: gateway #eureka中的服务名也是读取的此属性

server:
  port: 8001

eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:8761/eureka #eureka服务端地址

management:
  endpoints:
    web:
      exposure:
        include: routes #配置actuator，暴露routes端点，用来查看当前所有路由规则

zuul:
  routes:
    admin:
      path: /admin/** #定义路由转发规则
      url: admin #若输入url为localhost:8001/admin/**时,路由到服务名为admin的服务的对应的**url