spring:
  application:
    name: gateway

server:
  port: 8001

eureka:
  instance:
    preferIpAddress: true
  client:
    registerWithEureka: true
    fetchRegistry: true
    service-url:
      defaultZone: http://127.0.0.1:8761/eureka

zuul:
  routes:
    admin: /admin/**

management:
  security:
    enabled: false
  endpoints:
    web:
      exposure:
        include: routes